feat: added ginger db

diff --git a/.tekton/dry-run.yml b/.tekton/dry-run.yml
--- a/.tekton/dry-run.yml
+++ b/.tekton/dry-run.yml
@@ -3,33 +3,60 @@ kind: Task
 metadata:
   name: dry-run
   namespace: tasks-ginger-db-compose-runtime
-  annotations:
-    x-ginger-task-namespace: "ginger-db-compose-runtime"  # Custom annotation
-    x-ginger-task-trigger-branch: '["refs/heads/main"]'  # Allowed branches
-
 spec:
   workspaces:
       - name: source
       - name: ssh-credentials  # Store SSH keys
       - name: ssh-config  # Store SSH setup
-      - name: kubeconfig
-      - name: buildah-cache  # Workspace for caching
       - name: pipeline-secrets
       - name: general-purpose-cache
+      - name: src
   steps:
+
+    - name: clone
+      image: containers.gingersociety.org/secure-git-task-runner:latest
+      script: |
+        #!/bin/sh
+        set -e  # Exit on error
+
+        /usr/local/bin/configurator.sh
+        
+        git config --global init.defaultBranch main
+        git clone git@source.gingersociety.org:academy-database.git /workspace/source/repo
+        echo "Repository cloned successfully."
+
 
     - name: dry-run
       image: containers.gingersociety.org/gingersociety/ginger-db-compose-runtime:prod
       script: |
         #!/bin/sh
         set -e  # Exit on error
+        # cp /workspace/src/models.py /app/src/
+        rm -r /app/src/migrations
+        rm /app/src/admin.py
+        cp -r /workspace/source/repo/academy-iam/migrations /app/src/
 
         cd /app
+
+        ls -la src/migrations
+
+        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/installer.sh)" -- ginger-society/ginger-db:latest
+
+
+        ginger-db --help
+
+        ginger-db render-from-file --path /workspace/src/models.json --out /app/src/
+
 
         python manage.py makemigrations --verbosity 3
 
       securityContext:
         privileged: true
+
+  volumes:
+    - name: models-config
+      configMap:
+        name: dry-run-models
 
         
       
